server.port=8090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/microservices
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


management.tracing.sampling.probability=1