# Name of the Spring Boot application
spring.application.name=service-registry

# Port on which the server will run
server.port=8761

# Hostname for the Eureka instance
eureka.instance.hostname=localhost

# Do not register this instance with Eureka (useful for a standalone server)
eureka.client.register-with-eureka=false

# Do not fetch registry from Eureka (useful for a standalone server)
eureka.client.fetch-registry=false